apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  name: app-test-cert
spec:
  dnsNames:
  - inventory.bprof.gesz.dev
  - order.bprof.gesz.dev
  - db.bprof.gesz.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: app-test-cert
