apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  name: test-cert
  namespace: test-app-development
spec:
  dnsNames:
  - inventory.bprof.gesz.dev
  - order.bprof.gesz.dev
  - db.bprof.gesz.dev
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: test-cert
