apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: inventorymicroservice-servicemonitor
  labels:
    component: microservice
spec:
  selector:
    matchLabels:
      name: inventorymicroservice-service
  endpoints:
    - port: http
