apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ordermicroservice-servicemonitor
  labels:
    component: microservice
spec:
  selector:
    matchLabels:
      name: orderinterface-service
  endpoints:
    - port: http
