apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: eventstore/eventstore
  newTag: 20.6.1-buster-slim
- name: ghcr.io/bproforigoss/inventorymicroservice
  newTag: b98411a4b2e57ffcf9dfa5273bd8a7c7757d7be4
- name: ghcr.io/bproforigoss/ordermicroservice
  newTag: b98411a4b2e57ffcf9dfa5273bd8a7c7757d7be4

resources:
- k8sconfigs
- k8sdeployments
- k8sservices
- k8singress
- k8scerts
