apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: eventstore/eventstore
  newTag: 20.6.1-buster-slim
- name: ghcr.io/bproforigoss/inventorymicroservice
  newTag: c833a139967ddf32d15239ef6cdd2f7fabc4a610
- name: ghcr.io/bproforigoss/ordermicroservice
  newTag: c833a139967ddf32d15239ef6cdd2f7fabc4a610
- name: inventorymicroservice
  newTag: 7ee1c32916ed974aa4d080e5f13691203802775a
- name: ordermicroservice
  newTag: 7ee1c32916ed974aa4d080e5f13691203802775a

resources:
- k8sconfigs
- k8sdeployments
- k8sservices
- k8singress
- k8scerts
