apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: eventstore/eventstore
  newTag: 20.6.1-buster-slim
- name: ghcr.io/bproforigoss/inventorymicroservice
  newTag: d7cfce765c4288e7a34c968645d984f2dc2e33e0
- name: ghcr.io/bproforigoss/ordermicroservice
  newTag: d7cfce765c4288e7a34c968645d984f2dc2e33e0

resources:
- k8sconfigs
- k8sdeployments
- k8sservices
- k8singress
- k8scerts
