apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-app-development

images:
- name: eventstore/eventstore
  newTag: 20.6.1-buster-slim
- name: ghcr.io/bproforigoss/inventorymicroservice
  newTag: 4be4d18e96fac16e91cca649fa11cd02878bee15
- name: ghcr.io/bproforigoss/ordermicroservice
  newTag: 4be4d18e96fac16e91cca649fa11cd02878bee15

resources:
- k8sconfigs
- k8sdeployments
- k8sservices
- k8singress
- k8scerts
- prometheus
