apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-app-development

images:
- name: eventstore/eventstore
  newTag: 20.6.1-buster-slim
- name: ghcr.io/bproforigoss/inventorymicroservice
  newTag: 9109d824c3bad59c43cea5e0f2988bb2f30594a1
- name: ghcr.io/bproforigoss/ordermicroservice
  newTag: 9109d824c3bad59c43cea5e0f2988bb2f30594a1

resources:
- k8sconfigs
- k8sdeployments
- k8sservices
- k8singress
- k8scerts
- prometheus
