apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: eventstore/eventstore
  newTag: 20.6.1-buster-slim
- name: ghcr.io/bproforigoss/inventorymicroservice
  newTag: aa68f8c5857a3e551add9503f010be8992742e9a
- name: ghcr.io/bproforigoss/ordermicroservice
  newTag: aa68f8c5857a3e551add9503f010be8992742e9a

resources:
- k8sconfigs
- k8sdeployments
- k8sservices
- k8singress
- k8scerts
