apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: eventstore/eventstore
  newTag: 20.6.1-buster-slim
- name: ghcr.io/bproforigoss/inventorymicroservice
  newTag: 4496210a136e1fb22fcd9280a31fa8d39f85b289
- name: ghcr.io/bproforigoss/ordermicroservice
  newTag: 4496210a136e1fb22fcd9280a31fa8d39f85b289

resources:
- k8sconfigs
- k8sdeployments
- k8sservices
- k8singress
- k8scerts
