apiVersion: v1
kind: Service
metadata:
  name: eventstoredb-service
  namespace: test-app-development
spec:
  selector:
    app: eventstoredb
  ports:
    - protocol: TCP
      port: 2113
      targetPort: 2113
