apiVersion: v1
kind: Service
metadata:
  name: inventorymicroservice-service
  namespace: test-app-development
spec:
  selector:
    app: inventorymicroservice
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
