apiVersion: v1
kind: Service
metadata:
  name: ordermicroservice-service
  labels:
    app: ordermicroservice
spec:
  selector:
    app: ordermicroservice
  ports:
    - name: http
      port: 5001
      targetPort: http
