apiVersion: v1
kind: Service
metadata:
  name: ordermicroservice-service
  namespace: test-app-development
spec:
  selector:
    app: ordermicroservice
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
