apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventstore-deployment
  labels:
    app: eventstoredb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventstoredb
  template:
    metadata:
      labels:
        app: eventstoredb
    spec:
      containers:
      - name: eventstoredb
        image: eventstore/eventstore
        args: ["--insecure", "--enable-atom-pub-over-http"]
        livenessProbe:
          httpGet:
            port: 2113
            path: /health/live
        ports:
        - containerPort: 2113
