apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-app-development
  name: inventory-deployment
  labels:
    app: inventorymicroservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventorymicroservice
  template:
    metadata:
      labels:
        app: inventorymicroservice
    spec:
      containers:
      - name: inventory
        image: ghcr.io/bproforigoss/inventorymicroservice
        livenessProbe:
          httpGet:
            port: 5000
            path: /health
        ports:
        - containerPort: 5000
