apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-app-development
  name: inventory-deployment
  labels:
    app: inventorymicroservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventorymicroservice
  template:
    metadata:
      labels:
        app: inventorymicroservice
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: eventsourcing-testapp-configmap
      containers:
      - name: inventory
        image: ghcr.io/bproforigoss/inventorymicroservice:c833a139967ddf32d15239ef6cdd2f7fabc4a610
        env:
          - name: EVENTSTORE_WEBSCHEME
            valueFrom:
              configMapKeyRef:
                name: eventsourcing-testapp-configmap
                key: eventstoredb_webscheme
          - name: EVENTSTORE_URL
            valueFrom:
              configMapKeyRef:
                name: eventsourcing-testapp-configmap
                key: eventstoredb_location
          - name: EVENTSTORE_STREAM_PORT
            valueFrom:
              configMapKeyRef:
                name: eventsourcing-testapp-configmap
                key: eventstoredb_stream_port
          - name: EVENTSTORE_STREAM_URL
            value: "$(EVENTSTORE_WEBSCHEME)://$(EVENTSTORE_URL):$(EVENTSTORE_STREAM_PORT)/streams"
        volumeMounts:
          - name: config-volume
            mountPath: "/etc/config"
        livenessProbe:
          httpGet:
            port: 5000
            path: /health
        ports:
        - containerPort: 5000
