apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderinterface-deployment
  labels:
    app: ordermicroservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ordermicroservice
  template:
    metadata:
      labels:
        app: ordermicroservice
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: eventsourcing-testapp-configmap
      containers:
      - name: orderinterface
        image: ghcr.io/bproforigoss/ordermicroservice
        env:
          - name: EVENTSTORE_WEBSCHEME
            valueFrom:
              configMapKeyRef:
                name: eventsourcing-testapp-configmap
                key: eventstoredb_webscheme
          - name: EVENTSTORE_URL
            valueFrom:
              configMapKeyRef:
                name: eventsourcing-testapp-configmap
                key: eventstoredb_location
          - name: EVENTSTORE_STREAM_PORT
            valueFrom:
              configMapKeyRef:
                name: eventsourcing-testapp-configmap
                key: eventstoredb_stream_port
          - name: EVENTSTORE_STREAM_URL
            value: "$(EVENTSTORE_WEBSCHEME)://$(EVENTSTORE_URL):$(EVENTSTORE_STREAM_PORT)/streams"
        volumeMounts:
          - name: config-volume
            mountPath: "/etc/config"
        livenessProbe:
          httpGet:
            port: 5001
            path: /health
        ports:
        - containerPort: 5001
          name: http
