apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-app-development
  name: eventstore-deployment
  labels:
    app: eventstoredb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventstoredb
  template:
    metadata:
      labels:
        app: eventstoredb
    spec:
      containers:
      - name: eventstoredb
        image: eventstore/eventstore:20.6.1-buster-slim
        args: ["--insecure", "--enable-atom-pub-over-http"]
        ports:
        - containerPort: 2113
