apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-app-development
  name: orderinterface-deployment
  labels:
    app: ordermicroservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ordermicroservice
  template:
    metadata:
      labels:
        app: ordermicroservice
    spec:
      containers:
      - name: inventory
        image: ghcr.io/bproforigoss/ordermicroservice
        ports:
        - containerPort: 5001
