name: Build and Publish Docker images

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  
  build-services:
    
    name: Build Microservices Docker Images
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Build and Test Order Microservice
        run: |
          docker build --tag orderservice ./eventStoreTestApp/order_interface
          docker run --name orderservice -p 5001:5001 orderservice
          timeout 60 bash -c -- 'until $(curl -I --output /dev/null --silent --fail http://127.0.0.1:5001/order); do printf '.'; sleep 2; done'
          docker stop orderservice
        
      - name: Build and Test Inventory Microservice
        run: |
          docker build --tag inventoryservice ./eventStoreTestApp/inventory
          docker run --name inventoryservice -p 5000:5000 inventoryservice
          timeout 60 bash -c -- 'until $(curl -I --output /dev/null --silent --fail http://127.0.0.1:5000/inventory); do printf '.'; sleep 2; done'
          docker stop inventoryservice
