name: Build and Publish Docker images

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  
  build-test-services:
    
    name: Build and Test Microservices Docker Images
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Build and Test Order Microservice
        run: |
          docker build --tag orderservice ./eventStoreTestApp/order_interface
          docker run --detach --name orderservice -p 5001:5001 orderservice
          sleep 5s
          curl -I http://127.0.0.1:5001/order
          docker stop orderservice
        
      - name: Build and Test Inventory Microservice
        run: |
          docker build --tag inventoryservice ./eventStoreTestApp/inventory
          docker run --detach --name inventoryservice -p 5000:5000 inventoryservice
          sleep 5s
          curl -I http://127.0.0.1:5000/inventory
          docker stop inventoryservice

  build-push-action:
    
    name: Build and Push Images to GitHub Container Registry
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      
      - name: Push Order Microservice to GitHub Packages
        uses: docker/build-push-action@v2
        with:
            context: ./eventStoreTestApp/order_interface
            file: ./Dockerfile
            push: true
            tags: bproforigoss/ordermicroservice:latest
