name: Kubernetes Deployment

on:
  push:
    branches: [master]
    paths:
    - 'k8s/**'
  workflow_dispatch:

jobs:

  k8s-deploy-action:
    
    name: Set Up Environment and Apply Manifests
    runs-on: ubuntu-latest
    env:
      PRIV_KEY: ${{ secrets.PGP_PRIV_KEY }}

    steps:

      - name: Set up Go Environment
        uses: actions/setup-go@v1
        with:
          go-version: "1.15.6"

      - name: Install kubectl, kustomize and Secret OPerationS
        run: |
          sudo apt-get install kubectl
          wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.9.2/kustomize_v3.9.2_linux_amd64.tar.gz
          sudo tar -xf kustomize_v3.9.2_linux_amd64.tar.gz
          wget https://github.com/mozilla/sops/releases/download/v3.6.1/sops_3.6.1_amd64.deb
          sudo dpkg -i sops_3.6.1_amd64.deb

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Kubernetes Environment
        run: |
          echo "$PRIV_KEY" > private.key
          gpg --import private.key
          sops --decrypt --in-place ./kubeconfig
          
      - name: Deploy Infrastructure by Manifests
        run: |
          export KUBECONFIG=$(pwd)/kubeconfig
          ~/kustomize build ./k8s | kubectl apply -f -
