name: Kubernetes Deployment

on:
  push:
    branches: [master]
    paths:
    - 'k8s/**'
  workflow_dispatch:

jobs:

  k8s-deploy-action:
    
    name: Set Up Environment and Apply Manifests
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Set Cluster Credentials
        env:
          kubeconfig: ${{ secrets.KUBECONFIG }}
        run: |
          echo $kubeconfig
          echo $kubeconfig > kubeconfig
          cat kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig
      
      - name: Install kubectl
        run: |
          sudo apt-get install kubectl

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Infrastructure by Manifests
        run: |
          cd k8s
          echo $KUBECONFIG
          kubectl apply -f ./k8sconfigs/ -f ./k8scerts/ -f ./k8sdeployments/ -f ./k8sservices/ -f ./k8singress/
