name: Package Publishing

on:
  push:
    branches: [master]
    paths:
      - 'eventStoreTestApp/**'
  workflow_dispatch:

jobs:

  build-push-update-action:
    
    name: Build and Push Images to GHCR, Edit Infrastructure YAML
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push Order Microservice to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
            context: ./eventStoreTestApp/order_interface
            file: ./eventStoreTestApp/order_interface/Dockerfile
            push: true
            tags: ghcr.io/${{ github.repository_owner }}/ordermicroservice:${{ github.sha }}

      - name: Push Inventory Microservice to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
            context: ./eventStoreTestApp/inventory
            file: ./eventStoreTestApp/inventory/Dockerfile
            push: true
            tags: ghcr.io/${{ github.repository_owner }}/inventorymicroservice:${{ github.sha }}

      - name: Set New Version in Repository Infrastructure Description
        run: |
          cd k8s
          kustomize edit set image ghcr.io/${{ github.repository_owner }}/ordermicroservice:${{ github.sha }}
          kustomize edit set image ghcr.io/${{ github.repository_owner }}/inventorymicroservice:${{ github.sha }}

          git config --global user.name 'Automated CI/CD Agent'
          git config --global user.email 'kerteszdavid11@gmail.com'
          git commit -am "Automated kustomize edit for new SHA"
          git push
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/workflows/deployment.yaml/dispatches \
            -d '{"ref":"ref"}'
